import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/nav/TopNav";
import SideMenu from "@/components/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className='h-full'>
      <body className="flex flex-col bg-stone-200 h-full dark:bg-default-50">
      <Providers>
          <TopNav></TopNav>
          <div className="flex grow overflow-auto">
              <aside className="basis-1/6 shrink-0 border-r border-neutral-500 sticky top-0 px-6">
                  <SideMenu/>
              </aside>
              
              <main className="flex-1 pt-20 h-full">
                {children}
              </main>
              <aside className="basis-1/4 shrink-0 pt-20 sticky top-0 px-6 bg-stone-300 dark:bg-default-100">
                  Right Hand
              </aside>
          </div>
          
      </Providers>
      </body>
    </html>
  );
}
